#!/bin/bash
# Just print out the secrets file as-is if the password file doesn't exist
if [ ! -r '.vault_password' ]; then
    cat
    exit
fi

CONTENT="$(cat)"
# Store vault's stderr in RESULT and redirect decrypted stdout back to stdout
{
    RESULT="$(echo "$CONTENT" | ansible-vault decrypt - --vault-password-file=.vault_password 2>&1 1>&$OUT)";
} {OUT}>&1

if echo "$RESULT" | grep -qP "Decryption successful|^$"; then
    exit
elif echo "$RESULT" | grep -q "ERROR! input is not encrypted"; then
    echo "A secrets.yml file was committed in cleartext."
    echo "Please fix this before continuing."
    exit 1
else
    # This should be unreachable, but just in case.
    echo "RESULT=$RESULT" >> .gitdebug
    echo "CONTENT=$CONTENT" >> .gitdebug
    exit 1
fi
